# Config
# ========================================================================================

# IMPORTANT: Set the URL of your site.
# Set to https://<username>.github.io when hosting on GitHub Pages
# (unless you are using a custom domain).
url:                   https://lept1.github.io




# General settings
# ---------------------------------------------------------------------------------------

# Language of your content in 2-letter code, e.g.: en, de.
# You may also provide a location, e.g.: en-us, de_AT.
lang:                  en

# The title of your blog. Used in the sidebar and the browser tab.
title:                 Alessandro Dell'Orto

# A short description (~150 chars) of the page used for the meta description tag.
# Can use markdown, but no more than one paragraph (enforced by `>`)
description: I took my Master degree in Physiscs of Complex Systems at University of Torino in July 2020.
During these years I developed hard skills in Machine Learning, Game and Network Theory and Numerical Methods. 
My master thesis focused on modelling evolutionary games on graphs and simulating them numerically.

# A shorter description for the sidebar.
tagline:               AD

# A list of keywords for your blog
keywords:              [machine learning, game theory, graph theory, neural network, physics, quantum computing]

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  []

# This should be the same author as first entry in `_data/authors.yml`.
author:
  # Used by `jekyll-feed`:
  name:                Lept1
  # # Used by `jekyll-seo-tag`:
  # twitter:             <username>


# Add links to the footer.

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2020. All rights reserved.

# Format of the permalinks
permalink:             /:categories/:year-:month-:day-:title/

# Pagination configuration (used by the `blog` layout)
paginate:              10
paginate_path:         /:num/


# Collections
# ----------------------------------------------------------------------------------------

collections:
  featured_categories:
    permalink:         /:name/
    output:            true

  featured_tags:
    permalink:         /tag-:name/
    output:            true

  projects:
    permalink:         /projects/:path/
    output:            true


# Theme
# ---------------------------------------------------------------------------------------

theme: jekyll-theme-minimal
