# Config
# ========================================================================================

# IMPORTANT: Set the URL of your site.
# Set to https://<username>.github.io when hosting on GitHub Pages
# (unless you are using a custom domain).
url:                   https://lept1.github.io

logo: /assets/DellOrto_Alessandro.jpg


# General settings
# ---------------------------------------------------------------------------------------

# Language of your content in 2-letter code, e.g.: en, de.
# You may also provide a location, e.g.: en-us, de_AT.
lang:                  en

# The title of your blog. Used in the sidebar and the browser tab.
title:                 About me

# A short description (~150 chars) of the page used for the meta description tag.
# Can use markdown, but no more than one paragraph (enforced by `>`)
description: Don't wake me up when I'm coding

# A list of keywords for your blog
keywords:              [machine learning, game theory, graph theory, neural network, physics, quantum computing]

theme: jekyll-theme-minimal
